### ISSUE TITLE
Fix CrewU design with one line + navigation to sides + expand for most right icons

### ISSUE THREAD

**Issue by nigini** [nigini/stako#12]
Instead of adding extra lines of users in a crew, it seems to be better to create summarization (?10 more...?) (or pagination?) with arrows to each side of the banner.

Plus, currently, the icons presented to the right side seems to not have space to expand with mouseover.

**Comment by bbrusniak** [comment]
@nigini Issue fixed by adding a slider

**Comment by nigini** [comment]
Confirmed! Thanks, @bbrusniak
